<tr height="20px">
    <th>{num}</th>
    <th>
        <a>{fleet_name}</a>
    </th>
    <th>
        {fleet_proprio}
    </th>
    <th>
        <ul>
            {fleet_ships}
        </ul>
    </th>
    <th>
        {fleet_statut}
    </th>
    <th>
        inputs
    </th>
</tr>